apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 5m

  # Make FA wait on Postgres
  dependsOn:
    - name: postgres
      namespace: fusionauth

  volumes:
      - ./kickstart:/usr/local/fusionauth/kickstart

  chart:
    spec:
      chart: fusionauth
      # version: 1.59.1  # optional pin
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system
  targetNamespace: fusionauth
  values:
    # --- Database settings ---
    database:
      protocol: postgresql
      host: fusionauth-postgres-postgresql.fusionauth.svc.cluster.local
      port: 5432
      name: fusionauth
      # Application user (least-priv)
      user: fauser
      password: changeMeSuperSecret2
      root:
        user: postgres
        password: changeMeSuperSecret
    
    # Use database search (no Elasticsearch)
    search:
      engine: database

    kickstart:
      enabled: true

    app:
      runtimeMode: development

    # Simple exposure for EKS-A Docker
    service:
      type: NodePort
      port: 9011

    ingress:
      enabled: false


