apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 5m

  # Make FA wait on Postgres
  dependsOn:
    - name: postgres
      namespace: fusionauth

  chart:
    spec:
      chart: fusionauth
      # version: 1.59.1  # optional pin
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system
  targetNamespace: fusionauth
  values:
    # --- Database settings ---
    database:
      protocol: postgresql
      host: fusionauth-postgres-postgresql.fusionauth.svc.cluster.local
      port: 5432
      name: fusionauth
      # Application user (least-priv)
      user: fauser
      password: changeMeSuperSecret2
      root:
        user: postgres
        password: changeMeSuperSecret

    # Use database search (no Elasticsearch)
    search:
      engine: database

    kickstart:
      enabled: true

    app:
      runtimeMode: development

    # Simple exposure for EKS-A Docker
    service:
      type: NodePort
      port: 9011

    ingress:
      enabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: fusionauth-externalip
  namespace: fusionauth
spec:
  type: ClusterIP
  externalIPs:
    - 172.26.151.105        # VM's LAN IP (Hyper-V External switch)
  selector:
    app.kubernetes.io/name: fusionauth
    app.kubernetes.io/instance: fusionauth
  ports:
    - name: http
      port: 9011
      targetPort: 9011
      protocol: TCP


