apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 5m
  timeout: 5m

  dependsOn:
    - name: postgres
      namespace: fusionauth

  chart:
    spec:
      chart: fusionauth
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system
      # version: "*"  # optional: pin a version

  values:
    # ---------------------------
    # Database settings (example)
    # ---------------------------
    database:
      protocol: postgresql
      host: postgres-postgresql.fusionauth.svc.cluster.local
      port: 5432
      name: fusionauth
      user: fauser
      password: changeMeSuperSecret2
      root:
        user: postgres
        password: changeMeSuperSecre

    search:
      engine: database

    # Turn OFF the chart's native kickstart block to avoid an empty dir
    kickstart:
      enabled: false

    # (Optional) other chart values such as service, ingress, resources, etc.
    # service:
    #   type: ClusterIP
    #   port: 9011

  # Post-renderer: patch the rendered Deployment to mount our ConfigMap
  # and set FUSIONAUTH_APP_KICKSTART_FILE to the mounted JSON.
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              # This matches the FusionAuth chart's default Deployment name
              name: fusionauth-fusionauth
              namespace: fusionauth
            spec:
              template:
                spec:
                  volumes:
                    - name: kickstart
                      configMap:
                        name: fusionauth-kickstart
                        items:
                          - key: kickstart.json
                            path: kickstart.json
                          - key: styles.css
                            path: css/styles.css
                  containers:
                    # This matches the FusionAuth container name in the chart
                    - name: fusionauth
                      env:
                        - name: FUSIONAUTH_APP_KICKSTART_FILE
                          value: /usr/local/fusionauth/kickstart/kickstart.json
                        # Optional, helpful for demos
                        - name: FUSIONAUTH_APP_RUNTIME_MODE
                          value: development
                      volumeMounts:
                        - name: kickstart
                          mountPath: /usr/local/fusionauth/kickstart
                          readOnly: true

