apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 5m

  # Make FA wait on Postgres
  dependsOn:
    - name: postgres
      namespace: fusionauth

  chart:
    spec:
      chart: fusionauth
      # version: 1.59.1  # optional pin
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system
  targetNamespace: fusionauth
  values:
    # --- Database settings ---
    database:
      protocol: postgresql
      host: fusionauth-postgres-postgresql.fusionauth.svc.cluster.local
      port: 5432
      name: fusionauth
      # Application user (least-priv)
      user: fauser
      password: changeMeSuperSecret2
      root:
        user: postgres
        password: changeMeSuperSecret

    # Use database search (no Elasticsearch)
    search:
      engine: database

    kickstart:
      enabled: true
      files:
        kickstart.json |
          {
            "variables": {
              "apiKey": "33052c8a-c283-4e96-9d2a-eb1215c69f8f-not-for-prod",
              "asymmetricKeyId": "#{UUID()}",
              "applicationId": "e9fdb985-9173-4e01-9d73-ac2d60d1dc8e",
              "clientSecret": "super-secret-secret-that-should-be-regenerated-for-production",
              "newThemeId": "#{UUID()}",
              "defaultTenantId": "d7d09513-a3f5-401c-9685-34ab6c552453",
              "adminEmail": "admin@example.com",
              "adminPassword": "password",
              "adminUserId": "00000000-0000-0000-0000-000000000001",
              "userEmail": "richard@example.com",
              "userPassword": "password",
              "userUserId": "00000000-0000-0000-0000-111111111111"
            },
            "apiKeys": [
              {
                "key": "#{apiKey}",
                "description": "Unrestricted API key"
              }
            ],
            "requests": [
              { "method": "POST", "url": "/api/key/generate/#{asymmetricKeyId}", "tenantId": "#{defaultTenantId}", "body": { "key": { "algorithm": "RS256", "name": "For exampleapp", "length": 2048 } } },
              { "method": "POST", "url": "/api/application/#{applicationId}", "tenantId": "#{defaultTenantId}", "body": { "application": { "name": "ExampleDotNetApp", "oauthConfiguration": { "authorizedRedirectURLs": [ "http://localhost:5000/signin-oidc" ], "logoutURL": "http://localhost:5000/", "clientSecret": "#{clientSecret}", "enabledGrants": [ "authorization_code", "refresh_token" ], "generateRefreshTokens": true, "requireRegistration": true }, "jwtConfiguration": { "enabled": true, "accessTokenKeyId": "#{asymmetricKeyId}", "idTokenKeyId": "#{asymmetricKeyId}" } } } },
              { "method": "POST", "url": "/api/user/registration/#{adminUserId}", "body": { "registration": { "applicationId": "#{FUSIONAUTH_APPLICATION_ID}", "roles": [ "admin" ] }, "roles": [ "admin" ], "skipRegistrationVerification": true, "user": { "birthDate": "1981-06-04", "data": { "favoriteColor": "chartreuse" }, "email": "#{adminEmail}", "firstName": "Dinesh", "lastName": "Chugtai", "password": "#{adminPassword}" } } },
              { "method": "POST", "url": "/api/user/registration/#{userUserId}", "body": { "user": { "birthDate": "1985-11-23", "email": "#{userEmail}", "firstName": "Fred", "lastName": "Flintstone", "password": "#{userPassword}" }, "registration": { "applicationId": "#{applicationId}", "data": { "favoriteColor": "turquoise" } } } },
              { "method": "POST", "url": "/api/theme/#{newThemeId}", "body": { "sourceThemeId": "75a068fd-e94b-451a-9aeb-3ddb9a3b5987", "theme": { "name": "Changebank Theme" } } },
              { "method": "PATCH", "url": "/api/theme/#{newThemeId}", "body": { "theme": { "stylesheet": "@{css/styles.css}" } } },
              { "method": "PATCH", "url": "/api/tenant/#{defaultTenantId}", "body": { "tenant": { "themeId": "#{newThemeId}" } } }
            ]
          }

        css/styles.css |
          :root {
            --main-text-color: #424242;
            --main-accent-color: #096324;
            --input-background: #fbfbfb;
            --body-background: #f7f7f7;
            --tooltip-background: #e2e2e2;
            --error-color: #ff0000;
            --error-background: #ffe8e8;
            --border-color: #dddddd;
            --logo-url: url(https://fusionauth.io/cdn/samplethemes/changebank/changebank.svg);
            --font-stack: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
          }          

    env:
      name: FUSIONAUTH_APP_KICKSTART_FILE
      value: /usr/local/fusionauth/kickstart/kickstart.json

    app:
      runtimeMode: development

    # Simple exposure for EKS-A Docker
    service:
      type: NodePort
      port: 9011

    ingress:
      enabled: false

