apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
  # either pin an exact tag:
  ref:
    tag: 16.7.27
  # or prefer a moving range:
  # ref:
  #   semver: 16.x

