---
# Source namespace where you store the authoritative Secret
apiVersion: v1
kind: Namespace
metadata:
  name: source-secrets
---
# Authoritative source Secret (edit values here or create out-of-band)
apiVersion: v1
kind: Secret
metadata:
  name: fa-source-secrets
  namespace: source-secrets
type: Opaque
stringData:
  FA-root-db-username: "postgres"
  FA-root-db-password: "changeMeSuperSecret"
---
# Allow ESO to read Secrets in source-secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-k8s-reader
  namespace: source-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
  namespace: source-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-k8s-reader-binding
  namespace: source-secrets
subjects:
  - kind: ServiceAccount
    name: eso-k8s-reader
    namespace: source-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
---
# Namespaced SecretStore using the Kubernetes provider (points to source-secrets)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-source
  namespace: fusionauth
spec:
  provider:
    kubernetes:
      remoteNamespace: source-secrets
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-public
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-k8s-reader
          namespace: source-secrets
---
# Mirrors keys from the source Secret into fusionauth/fusionauth-secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fusionauth-secrets
  namespace: fusionauth
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: k8s-source
  target:
    name: fusionauth-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: FA_ROOT_DB_USERNAME
      remoteRef:
        key: fa-source-secrets
        property: FA-root-db-username
    - secretKey: FA_ROOT_DB_PASSWORD
      remoteRef:
        key: fa-source-secrets
        property: FA-root-db-password
