apiVersion: v1
kind: Namespace
metadata:
  name: fusionauth
---
apiVersion: external-secrets.io/v2beta1
kind: ExternalSecret
metadata:
  name: fusionauth-secrets
  namespace: fusionauth
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: fusionauth-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: FA_ROOT_DB_USERNAME
      remoteRef:
        key: FA-EKS-A-Secrets
        property: FA-root-db-username
    - secretKey: FA_ROOT_DB_PASSWORD
      remoteRef:
        key: FA-EKS-A-Secrets
        property: FA-root-db-password
