apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fusionauth            # or whatever namespace you use
resources:
  - 01-namespace.yaml
  - 02-postgres.yaml
  - 03-fusionauth.yaml
  - 04-fusionauth-helmrepository.yaml
  - 05-bitnami-helmrepository.yaml

configMapGenerator:
  - name: fusionauth-kickstart
    files:
      - kickstart.json=kickstart/kickstart.json
      - styles.css=kickstart/css/styles.css    # optional, keep adding more files as needed
generatorOptions:
  disableNameSuffixHash: true              # stable name so mounts don't break

